spring:
  datasource:
    Url: jdbc:mysql://localhost:3306/store-service-db?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-plataform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
